[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0.50"
anyhow = { version = "1.0.75", features = ["backtrace"] }
reqwest = { version = "0.11.22", features = ["blocking"] }
